import { OpenSourceProject } from '@/types';
import { calculateHealthScore } from './healthScore';

export const CURATED_PROJECTS: OpenSourceProject[] = [
  {
    id: 'shadcn_ui',
    owner: 'shadcn-ui',
    repo: 'ui',
    fullName: 'shadcn-ui/ui',
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
    stars: 84200,
    starVelocityMonth: 4800,
    forks: 7200,
    language: 'TypeScript',
    topics: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js'],
    difficulty: 'first_timers',
    license: 'MIT',
    githubUrl: 'https://github.com/shadcn-ui/ui',
    homepageUrl: 'https://ui.shadcn.com',
    healthScore: calculateHealthScore(1, 2.1, 92, 98, 420, 18),
    aiSummary:
      'A wildly popular collection of accessible React & Tailwind CSS UI primitives designed to be copied directly into your codebase rather than installed as an opaque npm dependency.',
    openGoodFirstIssues: [
      {
        id: 101,
        number: 4512,
        title: 'docs: Add interactive preview for new Carousel RTL orientation variant',
        url: 'https://github.com/shadcn-ui/ui/issues/4512',
        comments: 4,
        createdAt: '2026-08-18T10:00:00Z',
        labels: ['good first issue', 'documentation'],
      },
      {
        id: 102,
        number: 4530,
        title: 'fix(dialog): Improve focus trap restoration when closed via Escape key',
        url: 'https://github.com/shadcn-ui/ui/issues/4530',
        comments: 2,
        createdAt: '2026-08-20T14:30:00Z',
        labels: ['good first issue', 'bug'],
      },
    ],
    defaultGuide: {
      setupSteps: [
        'Fork repository on GitHub & clone: `git clone https://github.com/YOUR_USER/ui.git`',
        'Install dependencies using pnpm: `pnpm install`',
        'Launch docs development server: `pnpm --filter=docs dev` (runs at http://localhost:3000)',
      ],
      recommendedFirstIssue:
        'Start with docs improvements or adding missing prop types to components. These have immediate maintainer turnaround times.',
      codingConventions: [
        'Strict TypeScript validation across all component packages',
        'Radix UI accessibility primitive rules strictly enforced',
        'Pure Tailwind CSS utility styling — zero external CSS stylesheets',
      ],
      prTemplate: '## Changes Made\n\nCloses #[issue]\n\n- [Summary of changes]\n- Tested in latest Chrome / Firefox\n- Verified accessibility with screen reader',
      estimatedTime: '1 - 2 hours for first contribution',
    },
  },
  {
    id: 'vercel_ai',
    owner: 'vercel',
    repo: 'ai',
    fullName: 'vercel/ai',
    description: 'The AI SDK is the TypeScript toolkit designed to help you build AI-powered applications and agents.',
    stars: 18900,
    starVelocityMonth: 2100,
    forks: 1850,
    language: 'TypeScript',
    topics: ['TypeScript', 'React', 'Next.js', 'AI / LLM'],
    difficulty: 'beginner',
    license: 'Apache-2.0',
    githubUrl: 'https://github.com/vercel/ai',
    homepageUrl: 'https://sdk.vercel.ai',
    healthScore: calculateHealthScore(1, 1.8, 94, 95, 140, 12),
    aiSummary:
      'The foundational TypeScript toolkit for integrating LLM streaming, structured outputs, multi-modal chat, and autonomous tool calling into modern Next.js and React apps.',
    openGoodFirstIssues: [
      {
        id: 201,
        number: 1820,
        title: 'examples: Add Next.js 15 streaming tool invocation recipe with Gemini 1.5',
        url: 'https://github.com/vercel/ai/issues/1820',
        comments: 3,
        createdAt: '2026-08-19T08:00:00Z',
        labels: ['good first issue', 'examples'],
      },
    ],
    defaultGuide: {
      setupSteps: [
        'git clone https://github.com/YOUR_USER/ai.git',
        'pnpm install && pnpm build',
        'cd examples/next-openai && pnpm dev',
      ],
      recommendedFirstIssue: 'Example app recipes and model provider adapter documentation fixes.',
      codingConventions: ['Turborepo monorepo structure', '100% unit test coverage using Vitest'],
      prTemplate: '## AI SDK PR\n\n- Fixes #[issue]\n- Verified unit tests with `pnpm test`',
      estimatedTime: '2 - 3 hours',
    },
  },
  {
    id: 'tldraw_tldraw',
    owner: 'tldraw',
    repo: 'tldraw',
    fullName: 'tldraw/tldraw',
    description: 'A very good library for creating collaborative digital whiteboards and canvas tools in React.',
    stars: 38200,
    starVelocityMonth: 1600,
    forks: 2900,
    language: 'TypeScript',
    topics: ['TypeScript', 'React', 'Next.js'],
    difficulty: 'beginner',
    license: 'Apache-2.0',
    githubUrl: 'https://github.com/tldraw/tldraw',
    homepageUrl: 'https://tldraw.dev',
    healthScore: calculateHealthScore(2, 2.8, 89, 92, 190, 9),
    aiSummary:
      'A powerful React infinite canvas and digital whiteboard SDK with built-in multiplayer synchronization, gesture drawing, and extensibility hooks.',
    openGoodFirstIssues: [
      {
        id: 301,
        number: 3120,
        title: 'docs: Clarify custom shape binding lifecycle hooks in API reference',
        url: 'https://github.com/tldraw/tldraw/issues/3120',
        comments: 1,
        createdAt: '2026-08-15T12:00:00Z',
        labels: ['good first issue', 'docs'],
      },
    ],
  },
  {
    id: 'supabase_supabase',
    owner: 'supabase',
    repo: 'supabase',
    fullName: 'supabase/supabase',
    description: 'The open source Firebase alternative. Build production-grade backends in a weekend with Postgres.',
    stars: 76500,
    starVelocityMonth: 3200,
    forks: 6400,
    language: 'TypeScript',
    topics: ['TypeScript', 'Go', 'Docker', 'React', 'Next.js'],
    difficulty: 'intermediate',
    license: 'Apache-2.0',
    githubUrl: 'https://github.com/supabase/supabase',
    homepageUrl: 'https://supabase.com',
    healthScore: calculateHealthScore(1, 3.2, 88, 96, 780, 24),
    aiSummary:
      'An enterprise-grade open-source backend-as-a-service providing real-time PostgreSQL database hosting, instant GraphQL/REST APIs, authentication, and edge functions.',
    openGoodFirstIssues: [
      {
        id: 401,
        number: 14210,
        title: 'studio: Fix keyboard accessibility on SQL table column filter dropdown',
        url: 'https://github.com/supabase/supabase/issues/14210',
        comments: 5,
        createdAt: '2026-08-17T16:00:00Z',
        labels: ['good first issue', 'dashboard'],
      },
    ],
  },
  {
    id: 'calcom_calcom',
    owner: 'calcom',
    repo: 'cal.com',
    fullName: 'calcom/cal.com',
    description: 'Scheduling infrastructure for absolutely everyone. The open-source Calendly alternative.',
    stars: 34800,
    starVelocityMonth: 1400,
    forks: 8200,
    language: 'TypeScript',
    topics: ['TypeScript', 'Next.js', 'React', 'Tailwind CSS', 'GraphQL'],
    difficulty: 'beginner',
    license: 'AGPL-3.0',
    githubUrl: 'https://github.com/calcom/cal.com',
    homepageUrl: 'https://cal.com',
    healthScore: calculateHealthScore(1, 2.4, 91, 90, 310, 15),
    aiSummary:
      'A modern calendar scheduling platform that gives developers full control over their booking workflows, timezone scheduling, and payment integrations.',
    openGoodFirstIssues: [
      {
        id: 501,
        number: 9912,
        title: 'i18n: Add missing Spanish & French translation keys for attendee booking cancel confirmation',
        url: 'https://github.com/calcom/cal.com/issues/9912',
        comments: 2,
        createdAt: '2026-08-16T11:00:00Z',
        labels: ['good first issue', 'i18n'],
      },
    ],
  },
  {
    id: 'fastapi_fastapi',
    owner: 'fastapi',
    repo: 'fastapi',
    fullName: 'fastapi/fastapi',
    description: 'FastAPI framework, high performance, easy to learn, fast to code, ready for production in Python.',
    stars: 81200,
    starVelocityMonth: 2900,
    forks: 6800,
    language: 'Python',
    topics: ['Python', 'FastAPI'],
    difficulty: 'first_timers',
    license: 'MIT',
    githubUrl: 'https://github.com/fastapi/fastapi',
    homepageUrl: 'https://fastapi.tiangolo.com',
    healthScore: calculateHealthScore(3, 4.1, 85, 99, 520, 19),
    aiSummary:
      'The modern standard for building Python REST APIs with automatic OpenAPI schema generation, async concurrency, and Pydantic data validation.',
    openGoodFirstIssues: [
      {
        id: 601,
        number: 11400,
        title: 'docs: Update tutorial code snippets to use modern Python 3.12 type union syntax (X | Y)',
        url: 'https://github.com/fastapi/fastapi/issues/11400',
        comments: 6,
        createdAt: '2026-08-14T09:00:00Z',
        labels: ['good first issue', 'docs'],
      },
    ],
  },
  {
    id: 'langchain_ai',
    owner: 'langchain-ai',
    repo: 'langchain',
    fullName: 'langchain-ai/langchain',
    description: 'Build context-aware reasoning applications and agents with LLMs and vector stores.',
    stars: 96400,
    starVelocityMonth: 3800,
    forks: 15400,
    language: 'Python',
    topics: ['Python', 'TypeScript', 'AI / LLM'],
    difficulty: 'intermediate',
    license: 'MIT',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    homepageUrl: 'https://langchain.com',
    healthScore: calculateHealthScore(1, 2.0, 93, 91, 640, 22),
    aiSummary:
      'A widely adopted framework for building LLM applications, chaining prompts, querying vector embeddings, and running agentic workflows.',
    openGoodFirstIssues: [
      {
        id: 701,
        number: 22100,
        title: 'community: Add support for custom header forwarding in Mistral embedding provider',
        url: 'https://github.com/langchain-ai/langchain/issues/22100',
        comments: 3,
        createdAt: '2026-08-18T18:00:00Z',
        labels: ['good first issue', 'integrations'],
      },
    ],
  },
  {
    id: 'astral_uv',
    owner: 'astral-sh',
    repo: 'uv',
    fullName: 'astral-sh/uv',
    description: 'An extremely fast Python package and project manager, written in Rust.',
    stars: 42300,
    starVelocityMonth: 5100,
    forks: 1400,
    language: 'Rust',
    topics: ['Rust', 'Python'],
    difficulty: 'intermediate',
    license: 'Apache-2.0',
    githubUrl: 'https://github.com/astral-sh/uv',
    homepageUrl: 'https://docs.astral.sh/uv',
    healthScore: calculateHealthScore(1, 1.5, 96, 97, 180, 8),
    aiSummary:
      'A 10–100x faster drop-in replacement for pip, poetry, and virtualenv built with Rust to revolutionize the Python developer experience.',
    openGoodFirstIssues: [
      {
        id: 801,
        number: 4120,
        title: 'cli: Improve error message diagnostics when index URL contains trailing invalid spaces',
        url: 'https://github.com/astral-sh/uv/issues/4120',
        comments: 2,
        createdAt: '2026-08-19T20:00:00Z',
        labels: ['good first issue', 'diagnostics'],
      },
    ],
  },
  {
    id: 'tauri_tauri',
    owner: 'tauri-apps',
    repo: 'tauri',
    fullName: 'tauri-apps/tauri',
    description: 'Build smaller, faster, and more secure desktop and mobile applications with a web frontend.',
    stars: 83100,
    starVelocityMonth: 2700,
    forks: 3200,
    language: 'Rust',
    topics: ['Rust', 'TypeScript', 'React'],
    difficulty: 'intermediate',
    license: 'Apache-2.0',
    githubUrl: 'https://github.com/tauri-apps/tauri',
    homepageUrl: 'https://tauri.app',
    healthScore: calculateHealthScore(1, 2.9, 90, 94, 290, 14),
    aiSummary:
      'The lightweight Electron alternative allowing developers to build lightning-fast cross-platform desktop and mobile apps using web frontends with a Rust backend.',
    openGoodFirstIssues: [
      {
        id: 901,
        number: 8900,
        title: 'docs: Add guide for integrating Tailwind CSS v4 in Tauri 2.0 template',
        url: 'https://github.com/tauri-apps/tauri/issues/8900',
        comments: 4,
        createdAt: '2026-08-16T15:00:00Z',
        labels: ['good first issue', 'documentation'],
      },
    ],
  },
  {
    id: 'ollama_ollama',
    owner: 'ollama',
    repo: 'ollama',
    fullName: 'ollama/ollama',
    description: 'Get up and running with Llama 3, Mistral, Gemma, and other large language models locally.',
    stars: 98700,
    starVelocityMonth: 6200,
    forks: 8900,
    language: 'Go',
    topics: ['Go', 'AI / LLM', 'Docker'],
    difficulty: 'intermediate',
    license: 'MIT',
    githubUrl: 'https://github.com/ollama/ollama',
    homepageUrl: 'https://ollama.com',
    healthScore: calculateHealthScore(1, 2.2, 92, 93, 340, 11),
    aiSummary:
      'The easiest tool for bundling and serving local LLMs on macOS, Linux, and Windows with a native CLI and REST API server.',
    openGoodFirstIssues: [
      {
        id: 1001,
        number: 5410,
        title: 'api: Add structured response type example for custom system prompt streaming',
        url: 'https://github.com/ollama/ollama/issues/5410',
        comments: 3,
        createdAt: '2026-08-17T22:00:00Z',
        labels: ['good first issue', 'docs'],
      },
    ],
  },
];
