import { Medication } from '@/types';

export const INITIAL_MEDICATIONS: Medication[] = [
  {
    id: 'med_metformin',
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    dosage: '500mg',
    form: 'tablet',
    frequency: 'twice_daily',
    scheduledTimes: ['08:00', '20:00'],
    instructions: 'Take immediately with or after meals to minimize stomach upset',
    purpose: 'Type 2 Diabetes Blood Glucose Regulation',
    stockCount: 42,
    refillThreshold: 10,
    prescribingDoctor: 'Dr. Fatima Khan (Endocrinologist)',
    colorTag: 'emerald',
  },
  {
    id: 'med_lisinopril',
    name: 'Lisinopril',
    genericName: 'Lisinopril (ACE Inhibitor)',
    dosage: '10mg',
    form: 'tablet',
    frequency: 'once_daily',
    scheduledTimes: ['08:00'],
    instructions: 'Take once every morning with a full glass of water',
    purpose: 'Hypertension & Cardioprotective Blood Pressure Control',
    stockCount: 24,
    refillThreshold: 7,
    prescribingDoctor: 'Dr. Tariq Mahmood (Cardiologist)',
    colorTag: 'cyan',
  },
  {
    id: 'med_aspirin',
    name: 'Aspirin (Cardio)',
    genericName: 'Acetylsalicylic Acid',
    dosage: '81mg',
    form: 'tablet',
    frequency: 'once_daily',
    scheduledTimes: ['13:00'],
    instructions: 'Take daily after lunch; enteric-coated formulation',
    purpose: 'Secondary Stroke & Heart Attack Prevention',
    stockCount: 60,
    refillThreshold: 14,
    prescribingDoctor: 'Dr. Tariq Mahmood (Cardiologist)',
    colorTag: 'purple',
  },
  {
    id: 'med_atorvastatin',
    name: 'Atorvastatin (Lipitor)',
    genericName: 'Atorvastatin Calcium',
    dosage: '20mg',
    form: 'tablet',
    frequency: 'once_daily',
    scheduledTimes: ['22:00'],
    instructions: 'Take at bedtime for optimal hepatic cholesterol synthesis inhibition',
    purpose: 'Lipid & LDL Cholesterol Management',
    stockCount: 18,
    refillThreshold: 5,
    prescribingDoctor: 'Dr. Tariq Mahmood (Cardiologist)',
    colorTag: 'amber',
  },
  {
    id: 'med_ibuprofen',
    name: 'Ibuprofen',
    genericName: 'Ibuprofen (NSAID)',
    dosage: '400mg',
    form: 'capsule',
    frequency: 'as_needed',
    scheduledTimes: ['13:00'],
    instructions: 'Take with food for joint pain (Alert: Interacts with Lisinopril)',
    purpose: 'Arthritis & Joint Inflammation Relief',
    stockCount: 8,
    refillThreshold: 6,
    prescribingDoctor: 'Over-the-Counter (Patient Logged)',
    colorTag: 'rose',
  },
];
