'use client';

import { useState } from 'react';
import { ClassificationResult } from '@/types';
import { X, FileText, Printer, Copy, Check, Download, ShieldCheck, Stethoscope, Activity } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  result: ClassificationResult;
}

export default function StructuredReportModal({ isOpen, onClose, result }: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    return `# MEDVISION CLINICAL AI CONSULTATION REPORT
**Document ID**: REP-${result.id.toUpperCase()}
**Patient ID**: ${result.patientId || 'PX-84920-DX'}
**Examination Date**: ${result.studyDate || new Date().toISOString().split('T')[0]}
**Modality**: ${result.modalityCode || (result.modelType === 'xray' ? 'DX Digital Radiography' : 'DS Dermoscopy')}
**Neural Architecture**: ${result.gradcamLayerName}

---

## 1. PRIMARY DIAGNOSTIC IMPRESSION
- **Classification**: **${result.predictedClass}**
- **Algorithmic Confidence**: **${(result.confidence * 100).toFixed(1)}%**
- **Inference Latency**: ${result.inferenceTimeMs}ms (WebGL Accelerated)

---

## 2. MULTI-PATHOLOGY DIFFERENTIAL ANALYSIS
${
  result.differentialFindings && result.differentialFindings.length > 0
    ? result.differentialFindings
        .map(
          (f) => `### • ${f.condition} (${(f.probability * 100).toFixed(1)}% probability - ${f.riskLevel})
- **Anatomical Zone**: ${f.anatomicalLocation}
- **Clinical Significance**: ${f.clinicalSignificance}`
        )
        .join('\n\n')
    : Object.entries(result.probabilities)
        .map(([k, v]) => `- **${k}**: ${(v * 100).toFixed(1)}%`)
        .join('\n')
}

---

## 3. EXPLAINABILITY & GRADCAM HEATMAP LOCALIZATION
- **Target Conv Layer**: ${result.gradcamLayerName}
- **Peak Attention Zone**: ${result.educationalAnnotation?.anatomicalRegion || 'Primary Focal Region'}
- **Radiological Feature Correlation**: ${result.educationalAnnotation?.radiologyExplanation || 'N/A'}
- **Clinical Relevance**: ${result.educationalAnnotation?.clinicalRelevance || 'N/A'}

---

## 4. RECOMMENDED CLINICAL NEXT STEPS
${
  result.modelType === 'xray'
    ? `1. High-Resolution Chest CT (HRCT) to evaluate parenchymal extent of consolidation.
2. Complete Blood Count (CBC) and Blood/Sputum Cultures for targeted antibiotic therapy.
3. Pulse oximetry monitoring and serial follow-up radiograph in 48-72 hours.`
    : `1. Epiluminescence dermoscopic assessment under polarized cross-lighting.
2. Full-thickness excisional biopsy with 2mm margins for histopathological confirmation.
3. Staging evaluation (Breslow depth, ulceration status, mitotic rate).`
}

---
*MANDATORY DISCLAIMER: This document was generated by MedVision AI for educational, research, and clinical demonstration purposes only. It does not constitute a certified medical diagnosis and must always be verified by a board-certified physician.*`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-in fade-in duration-200 font-mono text-xs text-slate-300">
      <div className="relative w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-3xl bg-[#0b1220] border-2 border-cyan-500/40 p-6 sm:p-8 space-y-6 shadow-2xl shadow-cyan-500/20">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-white text-base font-outfit">
                Structured Radiology &amp; Pathology Consultation Report
              </h3>
              <p className="text-[11px] text-slate-400">
                Hospital PACS / DICOM-Standard Diagnostic Summary
              </p>
            </div>
          </div>

          <button onClick={onClose} className="p-2 rounded-xl bg-slate-950 border border-slate-800 text-slate-400 hover:text-white">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Clinical Document Preview */}
        <div className="p-6 rounded-2xl bg-[#05080e] border border-slate-800 space-y-6 text-[11px] font-sans text-slate-200 leading-relaxed shadow-inner">
          {/* DICOM Header Banner */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 rounded-xl bg-slate-950 border border-slate-900 font-mono text-[10px]">
            <div>
              <span className="text-slate-500 block">PATIENT ID</span>
              <strong className="text-white">{result.patientId || 'PX-84920-DX'}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">STUDY DATE</span>
              <strong className="text-white">{result.studyDate || '2026-08-21'}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">MODALITY</span>
              <strong className="text-cyan-400">{result.modalityCode || 'DX (Digital Radiography)'}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">INFERENCE TIME</span>
              <strong className="text-emerald-400">{result.inferenceTimeMs}ms</strong>
            </div>
          </div>

          {/* Primary Impression */}
          <div className="space-y-1.5 border-b border-slate-800/80 pb-4">
            <span className="text-[10px] font-bold text-cyan-400 uppercase font-mono tracking-wider">
              1. PRIMARY DIAGNOSTIC IMPRESSION
            </span>
            <div className="flex items-center justify-between flex-wrap gap-2">
              <h4 className="text-lg font-black text-white font-outfit">
                {result.predictedClass}
              </h4>
              <span className="px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 font-mono font-bold text-xs">
                {(result.confidence * 100).toFixed(1)}% Confidence
              </span>
            </div>
          </div>

          {/* Differential Diagnosis */}
          <div className="space-y-3 border-b border-slate-800/80 pb-4">
            <span className="text-[10px] font-bold text-slate-400 uppercase font-mono tracking-wider">
              2. DIFFERENTIAL PATHOLOGY SCREENING
            </span>
            <div className="space-y-2">
              {result.differentialFindings && result.differentialFindings.length > 0 ? (
                result.differentialFindings.map((f, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-slate-950/80 border border-slate-900 space-y-1">
                    <div className="flex items-center justify-between">
                      <strong className="text-white text-xs">{f.condition}</strong>
                      <span className="text-cyan-400 font-mono font-bold">{(f.probability * 100).toFixed(1)}%</span>
                    </div>
                    <p className="text-slate-400 text-[10px]">{f.clinicalSignificance}</p>
                  </div>
                ))
              ) : (
                Object.entries(result.probabilities).map(([k, v], idx) => (
                  <div key={idx} className="flex items-center justify-between p-2 rounded-lg bg-slate-950">
                    <span className="text-slate-300">{k}</span>
                    <span className="text-cyan-400 font-mono font-bold">{(v * 100).toFixed(1)}%</span>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* GradCAM Localization & Educational Notes */}
          <div className="space-y-2 border-b border-slate-800/80 pb-4">
            <span className="text-[10px] font-bold text-slate-400 uppercase font-mono tracking-wider">
              3. AI GRADCAM FEATURE ATTENTION &amp; CORRELATION
            </span>
            <p className="text-slate-300">
              {result.educationalAnnotation?.radiologyExplanation ||
                'Convolutional feature map gradients concentrated on the primary region of interest.'}
            </p>
          </div>

          {/* Disclaimer */}
          <div className="p-3 rounded-xl bg-slate-950 border border-slate-900 text-[10px] text-slate-500 font-mono">
            ⚠️ Educational simulator only. Not for clinical diagnostic use without radiologist confirmation.
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center justify-between flex-wrap gap-3 pt-1">
          <button
            type="button"
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-slate-900 border border-slate-700 hover:border-cyan-500 text-white font-bold flex items-center gap-1.5 transition-all cursor-pointer font-outfit"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown Report!' : 'Copy Markdown Report'}</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => window.print()}
              className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-400 to-blue-500 text-black font-bold flex items-center gap-1.5 shadow-md shadow-cyan-500/20 hover:scale-105 transition-all cursor-pointer font-outfit"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Official PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
