'use client';

import { useState } from 'react';
import { GroceryCategory, GroceryItem } from '@/types';
import {
  ShoppingCart,
  Check,
  Printer,
  Copy,
  Plus,
  Trash2,
  Sparkles,
  ShoppingBag,
  CheckCircle2,
} from 'lucide-react';

interface Props {
  categories: GroceryCategory[];
  onUpdateCategories?: (categories: GroceryCategory[]) => void;
}

export default function GroceryListBuilder({ categories: initialCategories, onUpdateCategories }: Props) {
  const [categories, setCategories] = useState<GroceryCategory[]>(initialCategories);
  const [hidePantry, setHidePantry] = useState(false);
  const [copied, setCopied] = useState(false);
  const [newItemName, setNewItemName] = useState('');
  const [selectedCatIdx, setSelectedCatIdx] = useState(0);

  const toggleItem = (catIdx: number, itemId: string) => {
    const updated = [...categories];
    const cat = updated[catIdx];
    cat.items = cat.items.map((item) =>
      item.id === itemId ? { ...item, checked: !item.checked } : item
    );
    setCategories(updated);
    onUpdateCategories?.(updated);
  };

  const togglePantryItem = (catIdx: number, itemId: string) => {
    const updated = [...categories];
    const cat = updated[catIdx];
    cat.items = cat.items.map((item) =>
      item.id === itemId ? { ...item, inPantry: !item.inPantry } : item
    );
    setCategories(updated);
    onUpdateCategories?.(updated);
  };

  const handleAddItem = () => {
    if (!newItemName.trim()) return;
    const updated = [...categories];
    if (updated[selectedCatIdx]) {
      updated[selectedCatIdx].items.push({
        id: 'g_' + Math.random().toString(36).slice(2, 9),
        name: newItemName.trim(),
        amount: '1 unit',
        checked: false,
        inPantry: false,
        estimatedPrice: 3.5,
      });
      setCategories(updated);
      onUpdateCategories?.(updated);
      setNewItemName('');
    }
  };

  // Generate Markdown Text for Export
  const generateMarkdown = () => {
    let md = `# SMART GROCERY SHOPPING LIST\nGenerated by NutriGenius.AI\n\n`;
    categories.forEach((cat) => {
      const itemsToInclude = hidePantry ? cat.items.filter((i) => !i.inPantry) : cat.items;
      if (itemsToInclude.length > 0) {
        md += `## ${cat.icon} ${cat.categoryName}\n`;
        itemsToInclude.forEach((item) => {
          md += `- [${item.checked ? 'x' : ' '}] **${item.name}** — ${item.amount}${item.inPantry ? ' *(In Pantry)*' : ''}\n`;
        });
        md += `\n`;
      }
    });
    return md;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Total items calculations
  const allItems = categories.flatMap((c) => c.items);
  const totalItemsCount = allItems.length;
  const checkedItemsCount = allItems.filter((i) => i.checked).length;
  const estimatedTotalCost = allItems
    .filter((i) => !i.inPantry)
    .reduce((sum, item) => sum + (item.estimatedPrice || 3.5), 0);

  return (
    <div className="space-y-6 font-sans">
      {/* Header Hub */}
      <div className="p-6 sm:p-8 rounded-3xl bg-[#09121d] border-2 border-emerald-500/30 shadow-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <span className="text-[10px] font-bold text-emerald-400 uppercase font-mono tracking-wider">
            Automated Supermarket Aggregator
          </span>
          <h2 className="text-xl sm:text-2xl font-black text-white font-outfit">
            Smart Grocery Shopping List
          </h2>
          <p className="text-xs text-slate-400">
            {checkedItemsCount} of {totalItemsCount} items completed • Estimated Cart: ~${estimatedTotalCost.toFixed(2)}
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2.5 flex-wrap">
          <button
            onClick={() => setHidePantry(!hidePantry)}
            className={`px-3.5 py-2 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
              hidePantry
                ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            {hidePantry ? '✓ Hiding Pantry Items' : 'Hide Pantry Staples'}
          </button>

          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 hover:border-emerald-500/40 text-slate-200 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied List!' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={() => window.print()}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-400 to-teal-500 text-black font-black text-xs shadow-md shadow-emerald-500/20 hover:scale-105 transition-all cursor-pointer flex items-center gap-1.5"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print List</span>
          </button>
        </div>
      </div>

      {/* Quick Add Custom Item */}
      <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 flex flex-col sm:flex-row items-center gap-3">
        <input
          value={newItemName}
          onChange={(e) => setNewItemName(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleAddItem()}
          placeholder="Add custom grocery item (e.g., Grass-fed ribeye, oat milk)..."
          className="flex-1 px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white text-xs placeholder-slate-500 focus:outline-none focus:border-emerald-500/50 w-full"
        />

        <select
          value={selectedCatIdx}
          onChange={(e) => setSelectedCatIdx(Number(e.target.value))}
          className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white text-xs focus:outline-none"
        >
          {categories.map((cat, i) => (
            <option key={i} value={i}>
              {cat.icon} {cat.categoryName}
            </option>
          ))}
        </select>

        <button
          onClick={handleAddItem}
          className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-bold text-xs transition-all cursor-pointer flex items-center gap-1 shrink-0"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>Add Item</span>
        </button>
      </div>

      {/* Categorized Aisle Checklist */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {categories.map((cat, catIdx) => {
          const visibleItems = hidePantry ? cat.items.filter((i) => !i.inPantry) : cat.items;
          if (visibleItems.length === 0) return null;

          return (
            <div
              key={cat.categoryName}
              className="p-6 rounded-3xl bg-[#09121d] border border-slate-800 space-y-4 shadow-xl"
            >
              {/* Category Header */}
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2">
                  <span className="text-xl">{cat.icon}</span>
                  <h3 className="font-extrabold text-white text-sm font-outfit">
                    {cat.categoryName}
                  </h3>
                </div>
                <span className="text-[10px] font-mono text-slate-400">
                  {visibleItems.filter((i) => i.checked).length}/{visibleItems.length} checked
                </span>
              </div>

              {/* Items List */}
              <div className="space-y-2">
                {visibleItems.map((item) => (
                  <div
                    key={item.id}
                    className={`p-3 rounded-2xl border transition-all flex items-center justify-between gap-3 text-xs ${
                      item.checked
                        ? 'bg-slate-950/40 border-slate-800 text-slate-500 line-through'
                        : 'bg-slate-950 border-slate-800/90 text-white hover:border-slate-700'
                    }`}
                  >
                    <div
                      onClick={() => toggleItem(catIdx, item.id)}
                      className="flex items-center gap-3 flex-1 cursor-pointer"
                    >
                      <div
                        className={`w-5 h-5 rounded-lg border flex items-center justify-center transition-all ${
                          item.checked
                            ? 'bg-emerald-500 border-emerald-500 text-black'
                            : 'border-slate-700 bg-slate-900'
                        }`}
                      >
                        {item.checked && <Check className="w-3 h-3 stroke-[3]" />}
                      </div>

                      <div>
                        <span className="font-bold font-outfit block">{item.name}</span>
                        <span className="text-[10px] text-slate-400 font-mono">{item.amount}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => togglePantryItem(catIdx, item.id)}
                        className={`px-2 py-0.5 rounded-lg text-[9px] font-mono font-bold border transition-colors cursor-pointer ${
                          item.inPantry
                            ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30'
                            : 'bg-slate-900 text-slate-500 border-slate-800 hover:text-slate-300'
                        }`}
                        title="Toggle in pantry"
                      >
                        {item.inPantry ? 'In Pantry' : '+ Pantry'}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
