'use client';

import { useState } from 'react';
import { PostMortem } from '@/types';
import {
  FileText,
  CheckCircle2,
  Clock,
  User,
  ShieldCheck,
  Download,
  Copy,
  Check,
  X,
  Sparkles,
  Calendar,
  Layers,
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface Props {
  postMortem: PostMortem;
  isOpen: boolean;
  onClose: () => void;
}

export default function PostMortemModal({ postMortem, isOpen, onClose }: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopyMarkdown = () => {
    const md = `# 📑 SRE Incident Post-Mortem: ${postMortem.title}
**Incident ID:** ${postMortem.incidentId} | **Severity:** ${postMortem.severity} | **Duration:** ${postMortem.durationMinutes} mins
**Lead Incident Commander:** ${postMortem.leadResponder}

---

## 1. Executive Summary
${postMortem.executiveSummary}

---

## 2. Root Cause & 5-Whys Analysis
${postMortem.fiveWhys.map((w) => `- ${w}`).join('\n')}

**Technical Details:**
${postMortem.rootCauseDetails}

---

## 3. Incident Timeline
${postMortem.timeline.map((t) => `- **${t.time}**: ${t.event}`).join('\n')}

---

## 4. Contributing Factors
${postMortem.contributingFactors.map((c) => `- ${c}`).join('\n')}

---

## 5. Corrective Action Items
${postMortem.actionItems.map((a) => `- [${a.status}] **${a.task}** (Owner: ${a.owner}, Due: ${a.dueDate})`).join('\n')}

---

## 6. Lessons Learned
${postMortem.lessonsLearned.map((l) => `- ${l}`).join('\n')}

---
*Generated by OpsPulse.AI SRE Incident Commander — Built by Abdul Nabi*
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    confetti({
      particleCount: 30,
      spread: 60,
      origin: { y: 0.7 },
      colors: ['#ef4444', '#10b981'],
    });
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-[#090d16] border border-rose-500/40 rounded-xl p-5 max-w-3xl w-full space-y-4 shadow-2xl my-8 font-mono text-xs text-slate-300 max-h-[90vh] flex flex-col">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-white/[0.08] pb-3.5 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-rose-500 to-amber-500 flex items-center justify-center text-black shadow-md font-bold">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-white text-sm font-mono">
                  {postMortem.title}
                </h3>
                <span className="px-2 py-0.5 rounded bg-rose-500/20 text-rose-400 border border-rose-500/30 text-[10px] font-bold font-mono">
                  {postMortem.severity}
                </span>
              </div>
              <p className="text-[10px] text-slate-400 font-mono">
                Blameless SRE Post-Incident Review • Lead Commander: {postMortem.leadResponder}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 rounded-lg bg-emerald-500 text-black font-extrabold text-xs flex items-center gap-1.5 hover:bg-emerald-400 transition-all cursor-pointer shadow-md font-mono"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Markdown!' : 'Export Post-Mortem'}</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-lg bg-[#0f1422] text-slate-400 hover:text-white transition-colors cursor-pointer border border-white/[0.08]"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto space-y-4 pr-1">
          {/* Executive Summary */}
          <div className="p-3.5 rounded-lg bg-[#0f1422] border border-white/[0.06] space-y-1">
            <span className="text-[10px] font-bold text-rose-400 uppercase font-mono">
              1. Executive Summary
            </span>
            <p className="text-white text-xs leading-relaxed prose-text">
              {postMortem.executiveSummary}
            </p>
          </div>

          {/* 5-Whys Root Cause Analysis */}
          <div className="p-3.5 rounded-lg bg-[#0f1422] border border-white/[0.06] space-y-1.5">
            <span className="text-[10px] font-bold text-amber-400 uppercase font-mono">
              2. Root Cause 5-Whys Diagnostic
            </span>
            <div className="space-y-1">
              {postMortem.fiveWhys.map((why, idx) => (
                <div key={idx} className="flex items-start gap-2 text-xs">
                  <span className="text-amber-400 font-bold font-mono">Q{idx + 1}:</span>
                  <span className="text-slate-200">{why}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Incident Timeline */}
          <div className="p-3.5 rounded-lg bg-[#0f1422] border border-white/[0.06] space-y-1.5">
            <span className="text-[10px] font-bold text-cyan-400 uppercase font-mono flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" />
              <span>3. Sequence of Events Timeline</span>
            </span>
            <div className="space-y-1 divide-y divide-white/[0.04]">
              {postMortem.timeline.map((item, idx) => (
                <div key={idx} className="flex items-center justify-between pt-1 text-[11px]">
                  <span className="font-bold text-cyan-300 font-mono">{item.time}</span>
                  <span className="text-slate-200 text-right">{item.event}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Corrective Action Items */}
          <div className="p-3.5 rounded-lg bg-[#0f1422] border border-white/[0.06] space-y-2">
            <span className="text-[10px] font-bold text-emerald-400 uppercase font-mono flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>4. Preventative &amp; Corrective Action Items</span>
            </span>
            <div className="space-y-1.5">
              {postMortem.actionItems.map((action, idx) => (
                <div
                  key={idx}
                  className="p-2 rounded bg-[#04080e] border border-white/[0.04] flex items-center justify-between gap-3 text-xs"
                >
                  <div className="space-y-0.5">
                    <span className="font-bold text-white">{action.task}</span>
                    <div className="flex items-center gap-3 text-[10px] text-slate-500 font-mono">
                      <span>Owner: <strong className="text-slate-300">{action.owner}</strong></span>
                      <span>Due: {action.dueDate}</span>
                    </div>
                  </div>

                  <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-300 border border-emerald-500/30 text-[9px] font-bold font-mono">
                    {action.status}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Lessons Learned */}
          <div className="p-3.5 rounded-lg bg-[#0f1422] border border-white/[0.06] space-y-1.5">
            <span className="text-[10px] font-bold text-purple-400 uppercase font-mono">
              5. Architectural Lessons Learned
            </span>
            <div className="space-y-1 text-xs">
              {postMortem.lessonsLearned.map((lesson, idx) => (
                <div key={idx} className="flex items-center gap-1.5">
                  <span className="text-purple-400">•</span>
                  <span className="text-slate-200">{lesson}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
