'use client';

import { useState } from 'react';
import { SEOAuditResult } from '@/types';
import { SAMPLE_ARTICLES } from '@/lib/sampleArticles';
import { runFullSEOAudit } from '@/lib/seoEngine';
import { RewriteMode, RewriteResponse } from '@/lib/gemini';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ArticleInput from '@/components/ArticleInput';
import SEOScoreOverview from '@/components/SEOScoreOverview';
import CompetitorBenchmarkCard from '@/components/CompetitorBenchmarkCard';
import NLPEntitiesCard from '@/components/NLPEntitiesCard';
import ReadabilityCard from '@/components/ReadabilityCard';
import KeywordDensityCard from '@/components/KeywordDensityCard';
import SERPPreviewCard from '@/components/SERPPreviewCard';
import HeadingTreeCard from '@/components/HeadingTreeCard';
import ActionPlanCard from '@/components/ActionPlanCard';
import AISectionRewriter from '@/components/AISectionRewriter';
import FAQSchemaGenerator from '@/components/FAQSchemaGenerator';
import AEOFAQSection from '@/components/AEOFAQSection';
import { Sparkles, Search, CheckCircle2, ArrowDown, RotateCcw, Download } from 'lucide-react';
import confetti from 'canvas-confetti';

export default function HomePage() {
  const [currentTitle, setCurrentTitle] = useState(SAMPLE_ARTICLES[0].title);
  const [currentTargetKeyword, setCurrentTargetKeyword] = useState(SAMPLE_ARTICLES[0].targetKeyword);
  const [currentContent, setCurrentContent] = useState(SAMPLE_ARTICLES[0].content);

  const [auditResult, setAuditResult] = useState<SEOAuditResult | null>(() =>
    runFullSEOAudit(
      SAMPLE_ARTICLES[0].content,
      SAMPLE_ARTICLES[0].targetKeyword,
      SAMPLE_ARTICLES[0].title,
      SAMPLE_ARTICLES[0].metaDescription,
      SAMPLE_ARTICLES[0].secondaryKeywords
    )
  );

  const [isLoadingAudit, setIsLoadingAudit] = useState<boolean>(false);
  const [isRewriting, setIsRewriting] = useState<boolean>(false);

  const handleRunAudit = async (
    title: string,
    targetKeyword: string,
    metaDescription: string,
    content: string,
    secondaryKeywords: string[]
  ) => {
    setCurrentTitle(title);
    setCurrentTargetKeyword(targetKeyword);
    setCurrentContent(content);
    setIsLoadingAudit(true);

    try {
      const res = await fetch('/api/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, targetKeyword, metaDescription, content, secondaryKeywords }),
      });

      const data: SEOAuditResult = await res.json();
      setAuditResult(data);

      confetti({
        particleCount: 30,
        spread: 60,
        origin: { y: 0.6 },
        colors: ['#10b981', '#06b6d4', '#f59e0b'],
      });
    } catch (err) {
      console.error('Audit failed, running client fallback:', err);
      const fallback = runFullSEOAudit(content, targetKeyword, title, metaDescription, secondaryKeywords);
      setAuditResult(fallback);
    } finally {
      setIsLoadingAudit(false);
    }
  };

  const handleRewrite = async (paragraph: string, targetKeyword: string, mode: RewriteMode): Promise<RewriteResponse> => {
    setIsRewriting(true);
    try {
      const res = await fetch('/api/rewrite', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ paragraph, targetKeyword, mode }),
      });

      const data: RewriteResponse = await res.json();
      return data;
    } catch (err) {
      console.error('Rewrite API failed:', err);
      throw err;
    } finally {
      setIsRewriting(false);
    }
  };

  // 1-Click Export Full SEO Audit Report (Markdown format)
  const handleExportReport = () => {
    if (!auditResult) return;

    const report = `# 📊 On-Page SEO Health & SERP Intelligence Report: ${currentTitle}
**Target Keyword:** ${auditResult.targetKeyword} | **Overall Score:** ${auditResult.overallScore}/100 (Grade: ${auditResult.grade})
**Generated By:** RankCraft.AI — Built by Abdul Nabi
**Audit Date:** ${new Date(auditResult.createdAt).toLocaleString()}

---

## 1. Executive Diagnostic Summary
${auditResult.headlineSummary}

- **Flesch Reading Ease:** ${auditResult.readability.fleschScore}/100 (${auditResult.readability.label})
- **Keyword Density:** ${auditResult.keywordDensity.densityPercent}% (${auditResult.keywordDensity.occurrences} occurrences)
- **Google E-E-A-T Score:** ${auditResult.eeat.compositeEEAT}/100 (Primary Intent: ${auditResult.eeat.searchIntent})
- **Total Word Count:** ${auditResult.readability.totalWords} words (~${auditResult.readability.readingTimeMinutes} min read)

---

## 2. Top-10 SERP Competitor Benchmarking
| Metric | Your Content | Top-10 SERP Average | Delta Status |
|:---|:---|:---|:---|
| **Word Count** | ${auditResult.competitorBenchmark.userWords} | ${auditResult.competitorBenchmark.avgTop10Words} | ${auditResult.competitorBenchmark.userWords >= auditResult.competitorBenchmark.avgTop10Words ? 'Optimal' : 'Needs Expansion'} |
| **Headings (H1–H3)** | ${auditResult.competitorBenchmark.userHeadings} | ${auditResult.competitorBenchmark.avgTop10Headings} | Balanced |
| **Flesch Ease** | ${auditResult.competitorBenchmark.userReadability} | ${auditResult.competitorBenchmark.avgTop10Readability} | ${auditResult.competitorBenchmark.userReadability >= 60 ? 'Plain English' : 'Complex'} |
| **Keyword Density** | ${auditResult.competitorBenchmark.userKeywordDensity}% | ${auditResult.competitorBenchmark.avgTop10KeywordDensity}% | Optimal |

---

## 3. Google NLP Semantic Entity Radar
- **Detected Entities:** ${auditResult.nlpEntities.coveredEntities.map((e) => `${e.name} (${e.count}x)`).join(', ')}
- **Recommended Content Gaps:** ${auditResult.nlpEntities.missingEntities.map((m) => m.name).join(', ')}

---

## 4. Prioritized SEO Action Roadmap
${auditResult.actionPlan
  .map(
    (item) =>
      `### #${item.priority} [${item.impact} IMPACT] ${item.category}\n- **Action:** ${item.action}\n- **Effort:** ${item.effort}`
  )
  .join('\n\n')}

---
*Report synthesized with RankCraft.AI on ${new Date().toISOString()}*
`;

    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SEO_Audit_${auditResult.targetKeyword.replace(/[^a-z0-9]/gi, '_')}.md`;
    a.click();
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#06090e] text-slate-200 font-mono">
      <Navbar onExportReport={handleExportReport} />

      <main className="flex-1 space-y-10 py-8 px-3 sm:px-6 max-w-7xl mx-auto w-full">
        {/* Hero Header */}
        <section className="text-center space-y-3.5 max-w-3xl mx-auto pt-2">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono font-bold">
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI CONTENT AUDIT &amp; SERP INTELLIGENCE SUITE</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-bold text-white tracking-tight font-mono leading-tight">
            Transform Blog Content into <br />
            <span className="bg-gradient-to-r from-emerald-400 via-teal-400 to-amber-400 bg-clip-text text-transparent">
              Top-Ranking Search Assets
            </span>
          </h1>

          <p className="text-xs sm:text-sm text-slate-400 font-mono max-w-2xl mx-auto leading-relaxed prose-text">
            Run comprehensive 8-point on-page SEO audits: Google E-E-A-T signals, NLP semantic entity coverage, Flesch-Kincaid readability, competitor SERP benchmarking, multi-mode AI rewrites, and Position 0 FAQ schemas.
          </p>
        </section>

        {/* Input Workbench */}
        <section className="rounded-3xl bg-[#090d16] border border-white/[0.08] p-5 sm:p-7 shadow-2xl shadow-emerald-500/5 sre-card">
          <ArticleInput onRunAudit={handleRunAudit} isLoading={isLoadingAudit} />
        </section>

        {/* Audit Results Section */}
        {auditResult && (
          <section id="results-dashboard" className="space-y-8 animate-in fade-in duration-500">
            {/* Scorecard Overview & GSC Predictor */}
            <SEOScoreOverview result={auditResult} />

            {/* Top-10 SERP Competitor Benchmarking Matrix */}
            <CompetitorBenchmarkCard benchmark={auditResult.competitorBenchmark} />

            {/* NLP Semantic Entity Coverage Radar */}
            <NLPEntitiesCard nlpEntities={auditResult.nlpEntities} />

            {/* Readability & Keyword Density Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <ReadabilityCard readability={auditResult.readability} />
              <KeywordDensityCard keywordDensity={auditResult.keywordDensity} />
            </div>

            {/* SERP Snippet Simulator & Heading Structure Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <SERPPreviewCard meta={auditResult.metaAudit} />
              <HeadingTreeCard structure={auditResult.headingStructure} />
            </div>

            {/* Multi-Mode AI Section Rewriter */}
            <AISectionRewriter
              paragraphs={auditResult.rawParagraphs}
              targetKeyword={auditResult.targetKeyword}
              onRewrite={handleRewrite}
              isLoading={isRewriting}
            />

            {/* Position 0 FAQ Schema Studio */}
            <FAQSchemaGenerator
              title={currentTitle}
              targetKeyword={currentTargetKeyword}
              content={currentContent}
            />

            {/* Prioritized SEO Action Plan */}
            <ActionPlanCard actionPlan={auditResult.actionPlan} />
          </section>
        )}

        {/* 100% AEO Crawlable Knowledge Hub Section */}
        <AEOFAQSection />
      </main>

      <Footer />
    </div>
  );
}
