'use client';

import { useState } from 'react';
import { TestResult } from '@/types';
import { Printer, Copy, Check, X, FileText, Sparkles } from 'lucide-react';

interface Props {
  result: TestResult;
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportReportModal({ result, isOpen, onClose }: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    const p = result.percentiles;
    return `# LOADPULSE.AI — EXECUTIVE LOAD TEST & PERFORMANCE AUDIT
**Generated:** ${new Date().toUTCString()}
**Target Endpoint:** \`${result.config.method} ${result.config.url}\`
**Virtual Users:** ${result.config.virtualUsers} VUs | **Duration:** ${result.config.durationSeconds}s | **Profile:** ${result.config.loadProfile}

---

## 📊 EXECUTIVE SUMMARY
- **Overall Verdict:** ${result.aiAnalysis?.verdict || 'PASS'}
- **Reliability Score:** ${result.aiAnalysis?.performanceScore || 85}/100
- **Total Requests:** ${result.totalRequests.toLocaleString()}
- **Throughput:** ${result.avgRps} avg RPS (Peak: ${result.peakRps} RPS)
- **Error Rate:** ${result.errorRate}% (${result.failedRequests} failed)

---

## ⏱️ RESPONSE TIME PERCENTILES (SLA)
| Percentile | Response Time | Description |
|---|---|---|
| **P50 (Median)** | \`${p.p50}ms\` | 50% of requests faster than this |
| **P90** | \`${p.p90}ms\` | 90% SLA baseline |
| **P95** | \`${p.p95}ms\` | 95% threshold |
| **P99 (Tail)** | \`${p.p99}ms\` | 99% tail latency |
| **Max** | \`${p.max}ms\` | Worst-case response |
| **Mean** | \`${p.mean}ms\` | Average response time |

---

## 🤖 AI ROOT-CAUSE & BOTTLENECK DIAGNOSTICS
${
  result.aiAnalysis?.bottlenecks?.length
    ? result.aiAnalysis.bottlenecks
        .map(
          (b) =>
            `### ⚠️ [${b.severity}] ${b.title}\n- **Evidence:** ${b.evidence}\n- **Root Cause:** ${b.rootCause}\n- **Remediation:** ${b.remediationStep}\n- **Estimated Improvement:** ${b.estimatedGain}\n`
        )
        .join('\n')
    : 'No critical bottlenecks detected. Endpoint sustained high concurrency reliably.'
}

---
*Report generated by LoadPulse.AI — Built by Abdul Nabi*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-200 font-sans">
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl glass-card border-2 border-cyan-500/40 p-6 sm:p-8 space-y-6 shadow-2xl">
        {/* Header */}
        <div className="flex items-start justify-between border-b border-white/[0.08] pb-4">
          <div className="space-y-1">
            <span className="text-[10px] font-bold text-cyan-400 uppercase font-mono tracking-wider">
              Executive Performance Audit Exporter
            </span>
            <h3 className="text-xl sm:text-2xl font-black text-white font-outfit">
              Load Test Stakeholder Report
            </h3>
            <p className="text-xs text-slate-400">
              Ready for executive review, engineering sign-off, or CI/CD compliance
            </p>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-950 border border-white/10 text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Quick Report Summary Badges */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono">
          <div className="p-3.5 rounded-2xl bg-slate-950/80 border border-white/5 text-center">
            <span className="text-lg font-black text-white block">{result.avgRps}</span>
            <span className="text-[10px] text-slate-400 uppercase font-bold">Avg RPS</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/80 border border-white/5 text-center">
            <span className="text-lg font-black text-emerald-400 block">{result.percentiles.p50}ms</span>
            <span className="text-[10px] text-slate-400 uppercase font-bold">P50 Latency</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/80 border border-white/5 text-center">
            <span className="text-lg font-black text-amber-400 block">{result.percentiles.p99}ms</span>
            <span className="text-[10px] text-slate-400 uppercase font-bold">P99 Tail</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/80 border border-white/5 text-center">
            <span className="text-lg font-black text-cyan-400 block">{result.errorRate}%</span>
            <span className="text-[10px] text-slate-400 uppercase font-bold">Error Rate</span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="flex-1 py-3 rounded-xl bg-slate-900 border border-white/10 hover:border-cyan-500/40 text-slate-200 text-xs font-bold flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied Markdown!' : 'Copy Markdown Audit'}</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex-1 py-3 rounded-xl bg-gradient-to-r from-cyan-400 to-blue-500 hover:from-cyan-300 hover:to-blue-400 text-black font-black text-xs shadow-lg shadow-cyan-500/20 hover:scale-105 transition-all cursor-pointer flex items-center justify-center gap-2"
          >
            <Printer className="w-4 h-4" />
            <span>Print PDF Report</span>
          </button>
        </div>
      </div>
    </div>
  );
}
