'use client';

import { useState } from 'react';
import { ArchitectureDesignResult } from '@/types';
import { Printer, Copy, Check, X, FileText, Download, ShieldCheck } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  architecture: ArchitectureDesignResult;
}

export default function SpecExportModal({ isOpen, onClose, architecture }: Props) {
  const [copiedMd, setCopiedMd] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    return `# System Design & Cloud Architecture Specification: ${architecture.title}

**Target Cloud Provider**: ${architecture.targetProvider}  
**Target Scale**: ${architecture.targetScale}  
**Projected Peak RPS**: ${architecture.projectedRPS.toLocaleString()} req/sec  
**Estimated P99 Latency**: ${architecture.estimatedP99Latency}  
**Projected Monthly Cost**: $${architecture.costBreakdown.totalMonthlyUSD.toLocaleString()}/month ($${(architecture.costBreakdown.totalMonthlyUSD * 12).toLocaleString()}/year)

---

## 1. Executive Architecture Summary
${architecture.requirementsSummary}

---

## 2. Multi-Tier Component Topology (${architecture.nodes.length} Services)
${architecture.nodes
  .map(
    (n) =>
      `### [Tier ${n.tier}] ${n.name} (${n.providerService})\n- **Type**: \`${n.type}\`\n- **Specs**: ${n.specs}\n- **Role**: ${n.description}`
  )
  .join('\n\n')}

---

## 3. Projected Monthly Cloud Cost Breakdown
| Category | Service | Specs | Estimated Monthly USD | Cost Driver |
|---|---|---|---|---|
${architecture.costBreakdown.items
  .map(
    (item) =>
      `| ${item.category} | ${item.serviceName} | ${item.specs} | $${item.estimatedMonthlyUSD}/mo | ${item.costDriver} |`
  )
  .join('\n')}

**Total Estimated Monthly Spend**: **$${architecture.costBreakdown.totalMonthlyUSD.toLocaleString()} USD**

---

## 4. High Availability & SPOF Vulnerability Audit
- **Overall Reliability Score**: ${architecture.spofAudit.overallReliabilityScore}/100
- **Recovery Point Objective (RPO)**: &le; ${architecture.spofAudit.rpoMinutes} Minutes
- **Recovery Time Objective (RTO)**: &le; ${architecture.spofAudit.rtoMinutes} Minutes

### Identified Vulnerabilities & Failover Protocols
${architecture.spofAudit.risks
  .map(
    (r) =>
      `#### ⚠️ ${r.componentName} (${r.severity} Severity)\n- **Vulnerability**: ${r.riskDescription}\n- **Failover Protocol**: ${r.failoverMitigation}`
  )
  .join('\n\n')}

---
*Generated by ArchCraft.AI — AI Cloud Architecture & System Design Studio*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200 font-mono text-xs text-slate-300">
      <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl bg-[#0b1220] border-2 border-cyan-500/40 p-6 sm:p-8 space-y-6 shadow-2xl shadow-cyan-500/20">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-white text-base font-outfit">System Design Architecture Specification Report</h3>
              <p className="text-xs text-slate-400">Export complete engineering whitepaper with topologies, cost run-rate, and DR SLA</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-950 border border-slate-800 text-slate-400 hover:text-white"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-700 hover:border-cyan-500 text-cyan-300 font-bold flex items-center gap-2 transition-all cursor-pointer"
          >
            {copiedMd ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copiedMd ? 'Copied Markdown Report' : 'Copy Markdown Report'}</span>
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-400 via-blue-500 to-indigo-500 text-black font-bold flex items-center gap-2 transition-all shadow-lg shadow-cyan-500/20 hover:scale-105 cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print to PDF</span>
          </button>
        </div>

        {/* Preview Markdown Box */}
        <pre className="p-6 rounded-2xl bg-slate-950 border border-slate-800 text-[11px] text-slate-200 font-mono overflow-x-auto max-h-[500px] leading-relaxed whitespace-pre-wrap">
          {generateMarkdownReport()}
        </pre>
      </div>
    </div>
  );
}
