import { MealAnalysisResult } from '@/types';

export interface SampleMeal {
  id: string;
  name: string;
  category: string;
  description: string;
  imageUrl: string;
  mockAnalysis: MealAnalysisResult;
}

export const SAMPLE_MEALS: SampleMeal[] = [
  {
    id: 'sample_salmon_bowl',
    name: 'Wild Alaskan Salmon & Quinoa Superfood Bowl',
    category: 'High Protein / Omega-3',
    description: 'Crispy skin salmon fillet, fluffy tri-color quinoa, sliced Haas avocado, steamed baby asparagus, and lemon herb olive oil dressing.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    mockAnalysis: {
      id: 'analysis_salmon_1',
      mealName: 'Wild Alaskan Salmon & Quinoa Superfood Bowl',
      mealType: 'lunch',
      timestamp: new Date().toISOString(),
      imageSrc: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
      items: [
        {
          name: 'Pan-Seared Wild Salmon Fillet',
          category: 'protein',
          estimatedGrams: 180,
          calories: 360,
          protein: 38,
          carbs: 0,
          fat: 22,
          fiber: 0,
          sugar: 0,
          sodiumMg: 140,
          confidence: 0.97,
          glycemicIndex: 'low',
        },
        {
          name: 'Steamed Tri-Color Quinoa',
          category: 'carbohydrate',
          estimatedGrams: 140,
          calories: 170,
          protein: 6.2,
          carbs: 31,
          fat: 2.8,
          fiber: 4.1,
          sugar: 0.8,
          sodiumMg: 12,
          confidence: 0.93,
          glycemicIndex: 'low',
        },
        {
          name: 'Sliced Fresh Haas Avocado',
          category: 'fat_oil',
          estimatedGrams: 60,
          calories: 96,
          protein: 1.2,
          carbs: 5.1,
          fat: 8.8,
          fiber: 4.0,
          sugar: 0.4,
          sodiumMg: 4,
          confidence: 0.95,
          glycemicIndex: 'low',
        },
        {
          name: 'Steamed Asparagus Spears',
          category: 'vegetable',
          estimatedGrams: 85,
          calories: 22,
          protein: 2.4,
          carbs: 3.8,
          fat: 0.2,
          fiber: 2.1,
          sugar: 1.6,
          sodiumMg: 6,
          confidence: 0.91,
          glycemicIndex: 'low',
        },
      ],
      totals: {
        calories: 648,
        protein: 47.8,
        carbs: 39.9,
        fat: 33.8,
        fiber: 10.2,
        sodiumMg: 162,
      },
      micros: {
        vitaminA_mcg: 480,
        vitaminC_mg: 28,
        vitaminD_IU: 680,
        vitaminB12_mcg: 4.2,
        iron_mg: 3.8,
        calcium_mg: 64,
        potassium_mg: 820,
        magnesium_mg: 110,
        zinc_mg: 2.6,
      },
      healthScore: 94,
      satietyRating: 'High',
      clinicalDietitianAdvice:
        'Outstanding cardioprotective meal rich in EPA/DHA Omega-3 fatty acids, complete amino acids, and high-fiber prebiotic carbohydrates. Low glycemic load ensures stable postprandial glucose levels.',
      optimizationSuggestions: [
        'Add a squeeze of fresh lemon juice to boost non-heme iron bioavailability.',
        'Pair with green tea or sparkling mineral water for polyphenol synergy.',
      ],
    },
  },
  {
    id: 'sample_chicken_salad',
    name: 'Mediterranean Grilled Chicken & Greek Feta Salad',
    category: 'Lean Muscle / Low Carb',
    description: 'Charbroiled chicken breast, authentic sheep feta cheese, kalamata olives, crisp Persian cucumbers, and cherry tomatoes.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    mockAnalysis: {
      id: 'analysis_chicken_1',
      mealName: 'Mediterranean Grilled Chicken & Greek Feta Salad',
      mealType: 'dinner',
      timestamp: new Date().toISOString(),
      imageSrc: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
      items: [
        {
          name: 'Herb-Marinated Grilled Chicken Breast',
          category: 'protein',
          estimatedGrams: 200,
          calories: 330,
          protein: 62,
          carbs: 0,
          fat: 7.2,
          fiber: 0,
          sugar: 0,
          sodiumMg: 210,
          confidence: 0.96,
          glycemicIndex: 'low',
        },
        {
          name: 'Authentic Crumbled Greek Feta',
          category: 'dairy',
          estimatedGrams: 45,
          calories: 120,
          protein: 6.5,
          carbs: 1.8,
          fat: 9.8,
          fiber: 0,
          sugar: 1.2,
          sodiumMg: 380,
          confidence: 0.92,
          glycemicIndex: 'low',
        },
        {
          name: 'Kalamata Olives & Extra Virgin Olive Oil',
          category: 'fat_oil',
          estimatedGrams: 30,
          calories: 110,
          protein: 0.4,
          carbs: 2.2,
          fat: 11.5,
          fiber: 1.2,
          sugar: 0,
          sodiumMg: 190,
          confidence: 0.89,
          glycemicIndex: 'low',
        },
        {
          name: 'Mixed Mediterranean Greens & Cucumbers',
          category: 'vegetable',
          estimatedGrams: 120,
          calories: 28,
          protein: 2.1,
          carbs: 4.8,
          fat: 0.3,
          fiber: 2.8,
          sugar: 2.4,
          sodiumMg: 20,
          confidence: 0.94,
          glycemicIndex: 'low',
        },
      ],
      totals: {
        calories: 588,
        protein: 71.0,
        carbs: 8.8,
        fat: 28.8,
        fiber: 4.0,
        sodiumMg: 800,
      },
      micros: {
        vitaminA_mcg: 620,
        vitaminC_mg: 35,
        vitaminD_IU: 20,
        vitaminB12_mcg: 1.1,
        iron_mg: 2.9,
        calcium_mg: 240,
        potassium_mg: 690,
        magnesium_mg: 65,
        zinc_mg: 3.1,
      },
      healthScore: 91,
      satietyRating: 'High',
      clinicalDietitianAdvice:
        'Exceptional high-protein lean profile (71g protein) with monounsaturated fats from extra virgin olive oil. Ideal for muscle recovery or ketogenic fat-adaptation.',
      optimizationSuggestions: [
        'Add a serving of walnuts or chia seeds if looking to boost plant-based alpha-linolenic acid (ALA).',
        'Watch sodium intake if tracking hypertension thresholds.',
      ],
    },
  },
  {
    id: 'sample_berry_acai',
    name: 'Organic Berry Protein & Seed Power Bowl',
    category: 'Antioxidant / Energy',
    description: 'Blended acai & whey protein base topped with fresh raspberries, organic hemp hearts, pumpkin seeds, and toasted coconut flakes.',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=800&q=80',
    mockAnalysis: {
      id: 'analysis_acai_1',
      mealName: 'Organic Berry Protein & Seed Power Bowl',
      mealType: 'breakfast',
      timestamp: new Date().toISOString(),
      imageSrc: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=800&q=80',
      items: [
        {
          name: 'Grass-Fed Whey Protein & Acai Base',
          category: 'protein',
          estimatedGrams: 220,
          calories: 240,
          protein: 28,
          carbs: 18,
          fat: 4.5,
          fiber: 5.2,
          sugar: 9.0,
          sodiumMg: 95,
          confidence: 0.95,
          glycemicIndex: 'low',
        },
        {
          name: 'Fresh Organic Raspberries & Blueberries',
          category: 'fruit',
          estimatedGrams: 80,
          calories: 45,
          protein: 0.9,
          carbs: 10.2,
          fat: 0.4,
          fiber: 5.8,
          sugar: 5.1,
          sodiumMg: 2,
          confidence: 0.97,
          glycemicIndex: 'low',
        },
        {
          name: 'Hemp Hearts & Raw Pumpkin Seeds',
          category: 'fat_oil',
          estimatedGrams: 30,
          calories: 165,
          protein: 9.2,
          carbs: 3.8,
          fat: 13.1,
          fiber: 2.4,
          sugar: 0.5,
          sodiumMg: 8,
          confidence: 0.91,
          glycemicIndex: 'low',
        },
      ],
      totals: {
        calories: 450,
        protein: 38.1,
        carbs: 32.0,
        fat: 18.0,
        fiber: 13.4,
        sodiumMg: 105,
      },
      micros: {
        vitaminA_mcg: 120,
        vitaminC_mg: 48,
        vitaminD_IU: 40,
        vitaminB12_mcg: 0.6,
        iron_mg: 4.5,
        calcium_mg: 180,
        potassium_mg: 540,
        magnesium_mg: 175,
        zinc_mg: 3.8,
      },
      healthScore: 96,
      satietyRating: 'High',
      clinicalDietitianAdvice:
        'Nutrient-dense morning bowl packed with anthocyanin antioxidants, 13.4g of prebiotic dietary fiber (nearly 50% daily target), and zinc/magnesium for cellular energy.',
      optimizationSuggestions: [
        'Optimal post-workout breakfast within 60 minutes of strength training.',
        'High magnesium content promotes muscle recovery and nervous system calm.',
      ],
    },
  },
];
