import { Incident } from '@/types';

export const SAMPLE_INCIDENTS: Incident[] = [
  {
    id: 'inc-9481',
    title: 'P1: PostgreSQL Connection Pool Exhaustion on payment-service',
    service: 'payment-service',
    severity: 'P1',
    status: 'investigating',
    startedAt: '2026-08-26T08:31:00Z',
    durationMinutes: 18,
    affectedUsers: 14200,
    revenueBurnRate: 4850,
    logs: [
      {
        id: 'l1',
        timestamp: '08:31:12.104',
        level: 'WARN',
        service: 'payment-service',
        pod: 'payment-service-7f89d4b-q9x12',
        message: 'DB pool checkout latency exceeded 2500ms (active: 98/100 connections)',
      },
      {
        id: 'l2',
        timestamp: '08:31:22.441',
        level: 'ERROR',
        service: 'payment-service',
        pod: 'payment-service-7f89d4b-q9x12',
        message: 'ERROR: remaining connection slots are reserved for non-replication superuser connections',
      },
      {
        id: 'l3',
        timestamp: '08:31:24.019',
        level: 'FATAL',
        service: 'payment-service',
        pod: 'payment-service-7f89d4b-mnk44',
        message: 'FATAL: sorry, too many clients already (current: 100, max_connections: 100)',
      },
      {
        id: 'l4',
        timestamp: '08:31:45.892',
        level: 'ERROR',
        service: 'payment-service',
        pod: 'payment-service-7f89d4b-q9x12',
        message: 'UnhandledPromiseRejection in processRefundBatch(): client connection acquired from pool was not released in finally block',
      },
      {
        id: 'l5',
        timestamp: '08:32:01.320',
        level: 'FATAL',
        service: 'checkout-api',
        pod: 'checkout-api-5c91f-8412a',
        message: 'HTTP 503 Service Unavailable upstream response from payment-service /v2/charge (100% failure rate on cart checkout)',
      },
      {
        id: 'l6',
        timestamp: '08:33:10.155',
        level: 'ERROR',
        service: 'payment-service',
        pod: 'payment-service-7f89d4b-k82p1',
        message: 'HikariCP-1 - Connection is not available, request timed out after 30000ms. Total: 100, Active: 100, Idle: 0, Waiting: 842',
      },
      {
        id: 'l7',
        timestamp: '08:34:05.719',
        level: 'WARN',
        service: 'ingress-nginx',
        pod: 'ingress-nginx-controller-74b88',
        message: 'upstream timed out (110: Connection timed out) while connecting to upstream payment-service:8080',
      },
    ],
    recentDeployments: [
      {
        id: 'dep-401',
        version: 'v2.4.1',
        service: 'payment-service',
        deployedAt: '2026-08-26T08:15:00Z',
        deployedBy: 'alex.sre@company.internal',
        commitHash: '7c89b14',
        commitMessage: 'feat(payments): add asynchronous bulk refund processing loop with automatic retry',
        riskScore: 'HIGH',
        prUrl: 'https://github.com/company/payment-service/pull/482',
      },
      {
        id: 'dep-400',
        version: 'v1.18.0',
        service: 'auth-service',
        deployedAt: '2026-08-26T06:00:00Z',
        deployedBy: 'ci-bot',
        commitHash: '1a2b3c4',
        commitMessage: 'chore: bump dependencies and nodejs runtime patch',
        riskScore: 'LOW',
      },
    ],
    diagnosis: {
      hypothesis:
        'PostgreSQL connection pool exhaustion in payment-service caused by an unclosed database client handle inside the newly deployed processRefundBatch() loop in v2.4.1.',
      confidence: 0.94,
      affectedService: 'payment-service',
      failureMode: 'CONNECTION_POOL_EXHAUSTION',
      evidenceFromLogs: [
        'FATAL: sorry, too many clients already (current: 100, max_connections: 100)',
        'UnhandledPromiseRejection in processRefundBatch(): client connection acquired from pool was not released in finally block',
        'HikariCP-1 - Connection is not available, request timed out after 30000ms. Waiting: 842',
      ],
      blastRadius: {
        primaryImpact: '100% of e-commerce checkout charges failing with HTTP 503 upstream timeout',
        secondaryImpact: [
          'Order processing worker queue accumulating backpressure',
          'Customer automated receipt emails stalled in RabbitMQ dead-letter exchange',
        ],
        estimatedUsersAffected: 14200,
        estimatedRevenuePerMin: 4850,
      },
      remediationSteps: [
        {
          step: 1,
          action: 'Rollback payment-service container deployment to stable v2.4.0',
          command: 'kubectl rollout undo deploy/payment-service -n production',
          expectedOutcome: 'Replaces leaking pods with stable release within 45 seconds',
          risk: 'LOW',
        },
        {
          step: 2,
          action: 'Terminate orphaned idle PostgreSQL client backend connections',
          command:
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle in transaction' AND application_name LIKE 'payment-service%';",
          expectedOutcome: 'Instantly frees up 80+ connection slots on PostgreSQL primary instance',
          risk: 'MEDIUM',
        },
        {
          step: 3,
          action: 'Verify payment-service health and checkout API success rate',
          command: 'curl -s https://api.internal/health/payment-service | jq .status',
          expectedOutcome: 'Returns HTTP 200 OK with active pool connections < 25%',
          risk: 'LOW',
        },
      ],
      deploymentCorrelation: {
        likelyCause: true,
        deployment: 'v2.4.1 (payment-service)',
        deployedAt: '08:15:00 UTC (16 mins prior to outage)',
        riskSignal: 'Introduced unhandled database client acquisition loop without finally { client.release() }',
      },
    },
    comms: {
      slackMessage:
        '🚨 *INCIDENT ALERT — P1 CRITICAL*\n*Service:* `payment-service`\n*Impact:* 100% checkout failure rate (~14.2k users affected, $4,850/min burn)\n*Root Cause Hypothesis:* HikariCP connection pool exhaustion in v2.4.1 `processRefundBatch`\n*Action in Progress:* Rolling back to `v2.4.0` and terminating stuck idle transactions.\n*War Room:* https://meet.google.com/sre-incident-p1',
      executiveBrief:
        'Executive Briefing: We are actively resolving a P1 outage affecting payment processing. Total estimated revenue impacted is ~$4,850/min. SRE team has initiated a code rollback to the previous stable release. Full recovery expected within 5 minutes.',
      statusPageUpdate:
        'Investigating: We are currently investigating an issue affecting customer checkout and payment processing. Our engineering team has identified the cause and is applying a fix. Next update in 10 minutes.',
    },
    topology: {
      nodes: [
        { id: 'n1', name: 'Cloudflare Edge CDN', type: 'edge', status: 'healthy', latencyMs: 14, throughputRps: 8400, errorRatePercent: 0.01, technology: 'Anycast Edge' },
        { id: 'n2', name: 'Ingress NGINX', type: 'gateway', status: 'degraded', latencyMs: 240, throughputRps: 4200, errorRatePercent: 48.2, technology: 'Kubernetes Ingress' },
        { id: 'n3', name: 'checkout-api', type: 'service', status: 'degraded', latencyMs: 2850, throughputRps: 1850, errorRatePercent: 96.4, podCount: '6/6 Running', technology: 'Node.js Express' },
        { id: 'n4', name: 'payment-service', type: 'service', status: 'critical', latencyMs: 3450, throughputRps: 1420, errorRatePercent: 100.0, podCount: '3/3 Saturated', technology: 'Spring Boot 3.2' },
        { id: 'n5', name: 'PostgreSQL Primary', type: 'database', status: 'critical', latencyMs: 30000, throughputRps: 100, errorRatePercent: 100.0, podCount: 'AWS RDS Aurora', technology: 'PostgreSQL 16' },
        { id: 'n6', name: 'Redis Cache Cluster', type: 'cache', status: 'healthy', latencyMs: 2, throughputRps: 9200, errorRatePercent: 0.0, technology: 'Redis 7.2' },
        { id: 'n7', name: 'RabbitMQ DeadLetter', type: 'queue', status: 'degraded', latencyMs: 45, throughputRps: 640, errorRatePercent: 24.1, technology: 'RabbitMQ' },
      ],
      edges: [
        { id: 'e1', source: 'n1', target: 'n2', latencyMs: 14, status: 'healthy' },
        { id: 'e2', source: 'n2', target: 'n3', latencyMs: 240, status: 'degraded' },
        { id: 'e3', source: 'n3', target: 'n4', latencyMs: 2850, status: 'critical' },
        { id: 'e4', source: 'n4', target: 'n5', latencyMs: 30000, status: 'critical' },
        { id: 'e5', source: 'n4', target: 'n6', latencyMs: 2, status: 'healthy' },
        { id: 'e6', source: 'n4', target: 'n7', latencyMs: 45, status: 'degraded' },
      ],
    },
    telemetry: [
      { timestamp: '08:20', errorRate: 0.02, p95Latency: 38, p99Latency: 64, resourceSaturation: 18.0 },
      { timestamp: '08:24', errorRate: 0.04, p95Latency: 42, p99Latency: 72, resourceSaturation: 22.4 },
      { timestamp: '08:28', errorRate: 0.12, p95Latency: 85, p99Latency: 140, resourceSaturation: 48.2 },
      { timestamp: '08:31', errorRate: 44.8, p95Latency: 890, p99Latency: 1840, resourceSaturation: 98.0 },
      { timestamp: '08:32', errorRate: 98.4, p95Latency: 2850, p99Latency: 3820, resourceSaturation: 100.0 },
      { timestamp: '08:33', errorRate: 99.8, p95Latency: 3450, p99Latency: 4200, resourceSaturation: 100.0 },
      { timestamp: '08:34', errorRate: 100.0, p95Latency: 3500, p99Latency: 4300, resourceSaturation: 100.0 },
    ],
    errorBudget: {
      targetSlo: 99.9,
      periodDays: 30,
      totalBudgetMinutes: 43.2,
      minutesBurned: 18.0,
      burnRateMultiplier: 14.4,
      estimatedExhaustionHours: 2.4,
    },
  },
  {
    id: 'inc-9482',
    title: 'P2: Kubernetes OOMKilled CrashLoopBackOff on auth-service',
    service: 'auth-service',
    severity: 'P2',
    status: 'investigating',
    startedAt: '2026-08-26T07:45:00Z',
    durationMinutes: 32,
    affectedUsers: 8900,
    revenueBurnRate: 1650,
    logs: [
      {
        id: 'l10',
        timestamp: '07:45:10.220',
        level: 'WARN',
        service: 'auth-service',
        pod: 'auth-service-684b-01',
        message: 'Node cgroup memory pressure warning: container memory usage at 96.8% (508Mi / 512Mi)',
      },
      {
        id: 'l11',
        timestamp: '07:45:14.881',
        level: 'FATAL',
        service: 'kubelet',
        pod: 'auth-service-684b-01',
        message: 'Container auth-service in pod auth-service-684b-01 was OOMKilled (exit code 137). Restart count: 4',
      },
      {
        id: 'l12',
        timestamp: '07:45:30.400',
        level: 'ERROR',
        service: 'gateway',
        pod: 'api-gateway-11a',
        message: '502 Bad Gateway while proxying /v1/oauth/token — upstream pod restarting in CrashLoopBackOff',
      },
      {
        id: 'l13',
        timestamp: '07:46:01.012',
        level: 'ERROR',
        service: 'auth-service',
        pod: 'auth-service-684b-02',
        message: 'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory',
      },
    ],
    recentDeployments: [
      {
        id: 'dep-395',
        version: 'v3.1.0',
        service: 'auth-service',
        deployedAt: '2026-08-26T07:20:00Z',
        deployedBy: 'sarah.dev@company.internal',
        commitHash: '8e4f1a2',
        commitMessage: 'feat(jwt): cache in-memory JWKS public keys without TTL eviction limit',
        riskScore: 'HIGH',
        prUrl: 'https://github.com/company/auth-service/pull/219',
      },
    ],
    diagnosis: {
      hypothesis:
        'Node.js V8 Heap memory leak in auth-service v3.1.0 caused by unbound JWKS key caching in RAM leading to kernel cgroup OOMKill (Exit 137).',
      confidence: 0.96,
      affectedService: 'auth-service',
      failureMode: 'OOM_KILLED',
      evidenceFromLogs: [
        'Container auth-service in pod auth-service-684b-01 was OOMKilled (exit code 137)',
        'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory',
      ],
      blastRadius: {
        primaryImpact: '502 Bad Gateway on user login and OAuth token refreshes',
        secondaryImpact: ['Mobile app session renewals failing across iOS/Android clients'],
        estimatedUsersAffected: 8900,
        estimatedRevenuePerMin: 1650,
      },
      remediationSteps: [
        {
          step: 1,
          action: 'Scale up Pod Memory Limit temporarily from 512Mi to 2Gi',
          command:
            'kubectl set resources deployment auth-service --limits=memory=2Gi,cpu=1000m -n production',
          expectedOutcome: 'Stops instantaneous OOMKill cycling while team patches code',
          risk: 'LOW',
        },
        {
          step: 2,
          action: 'Rollback auth-service to v3.0.4 with bounded cache',
          command: 'kubectl rollout undo deploy/auth-service -n production',
          expectedOutcome: 'Restores memory stability and resolves crash loops',
          risk: 'LOW',
        },
      ],
      deploymentCorrelation: {
        likelyCause: true,
        deployment: 'v3.1.0 (auth-service)',
        deployedAt: '07:20:00 UTC (25 mins prior)',
        riskSignal: 'Unbounded in-memory map storing public certificates on every handshake',
      },
    },
    comms: {
      slackMessage:
        '⚠️ *INCIDENT ALERT — P2 HIGH*\n*Service:* `auth-service`\n*Impact:* User login and token refresh degradation (OOMKill Exit 137)\n*Remediation:* Bumping memory limits to 2Gi and rolling back to v3.0.4.',
      executiveBrief:
        'P2 incident active on user authentication. Engineering has increased container memory allocation and initiated a rollback to restore login stability.',
      statusPageUpdate:
        'Identified: Users may experience delays or errors when attempting to sign in. A fix is currently being deployed to resolve the authentication service memory bottleneck.',
    },
    topology: {
      nodes: [
        { id: 'n1', name: 'Global Traffic Edge', type: 'edge', status: 'healthy', latencyMs: 18, throughputRps: 6500, errorRatePercent: 0.05, technology: 'Cloudflare CDN' },
        { id: 'n2', name: 'Kong API Gateway', type: 'gateway', status: 'degraded', latencyMs: 620, throughputRps: 3400, errorRatePercent: 58.2, technology: 'Kong Gateway' },
        { id: 'n3', name: 'auth-service', type: 'service', status: 'critical', latencyMs: 2400, throughputRps: 1200, errorRatePercent: 88.5, podCount: '1/3 CrashLoop', technology: 'Node.js v20' },
        { id: 'n4', name: 'User Directory DB', type: 'database', status: 'healthy', latencyMs: 4, throughputRps: 1800, errorRatePercent: 0.0, technology: 'PostgreSQL Aurora' },
        { id: 'n5', name: 'Session Token Cache', type: 'cache', status: 'healthy', latencyMs: 1, throughputRps: 4200, errorRatePercent: 0.0, technology: 'Redis Cluster' },
      ],
      edges: [
        { id: 'e1', source: 'n1', target: 'n2', latencyMs: 18, status: 'healthy' },
        { id: 'e2', source: 'n2', target: 'n3', latencyMs: 620, status: 'degraded' },
        { id: 'e3', source: 'n3', target: 'n4', latencyMs: 4, status: 'healthy' },
        { id: 'e4', source: 'n3', target: 'n5', latencyMs: 1, status: 'healthy' },
      ],
    },
    telemetry: [
      { timestamp: '07:35', errorRate: 0.01, p95Latency: 28, p99Latency: 48, resourceSaturation: 42.0 },
      { timestamp: '07:40', errorRate: 0.05, p95Latency: 35, p99Latency: 60, resourceSaturation: 68.4 },
      { timestamp: '07:44', errorRate: 12.0, p95Latency: 420, p99Latency: 950, resourceSaturation: 96.8 },
      { timestamp: '07:45', errorRate: 64.2, p95Latency: 1450, p99Latency: 2200, resourceSaturation: 99.8 },
      { timestamp: '07:46', errorRate: 88.5, p95Latency: 2400, p99Latency: 3100, resourceSaturation: 100.0 },
    ],
    errorBudget: {
      targetSlo: 99.9,
      periodDays: 30,
      totalBudgetMinutes: 43.2,
      minutesBurned: 12.5,
      burnRateMultiplier: 9.8,
      estimatedExhaustionHours: 3.8,
    },
  },
  {
    id: 'inc-9483',
    title: 'P3: Edge Ingress TLS Handshake Timeout & DNS Latency',
    service: 'gateway-ingress',
    severity: 'P3',
    status: 'investigating',
    startedAt: '2026-08-26T06:10:00Z',
    durationMinutes: 45,
    affectedUsers: 3400,
    revenueBurnRate: 420,
    logs: [
      {
        id: 'l20',
        timestamp: '06:10:05.101',
        level: 'WARN',
        service: 'gateway-ingress',
        pod: 'ingress-edge-01',
        message: 'SSL handshake latency to upstream Cloudflare origin exceeded 1800ms',
      },
      {
        id: 'l21',
        timestamp: '06:10:22.404',
        level: 'ERROR',
        service: 'gateway-ingress',
        pod: 'ingress-edge-01',
        message: '504 Gateway Timeout during TLS renegotiation with eu-central origin cluster',
      },
    ],
    recentDeployments: [],
    diagnosis: {
      hypothesis:
        'Cross-region TLS session resumption latency between Cloudflare Edge and primary EU-Central origin ingress gateway.',
      confidence: 0.88,
      affectedService: 'gateway-ingress',
      failureMode: 'DNS_TIMEOUT',
      evidenceFromLogs: [
        'SSL handshake latency to upstream Cloudflare origin exceeded 1800ms',
        '504 Gateway Timeout during TLS renegotiation',
      ],
      blastRadius: {
        primaryImpact: 'Intermittent latency spikes for European region website visitors',
        secondaryImpact: ['Static asset CDN cache miss rate elevated by 14%'],
        estimatedUsersAffected: 3400,
        estimatedRevenuePerMin: 420,
      },
      remediationSteps: [
        {
          step: 1,
          action: 'Enable TLS 1.3 0-RTT session tickets on NGINX Ingress',
          command:
            'kubectl patch configmap nginx-configuration -n ingress-nginx --patch \'{"data":{"ssl-session-tickets":"on","ssl-protocols":"TLSv1.2 TLSv1.3"}}\'',
          expectedOutcome: 'Eliminates one roundtrip on recurring client handshakes',
          risk: 'LOW',
        },
      ],
    },
    comms: {
      slackMessage:
        'ℹ️ *P3 NOTICE:* Edge ingress TLS latency in EU region under observation. Applied TLS 1.3 session ticket patch.',
      executiveBrief:
        'P3 minor latency impact in European region. Engineering applied TLS configuration optimizations.',
      statusPageUpdate:
        'Monitoring: We have implemented an edge routing optimization and are observing improved response times in the European region.',
    },
    topology: {
      nodes: [
        { id: 'n1', name: 'EU Cloudflare PoP', type: 'edge', status: 'degraded', latencyMs: 380, throughputRps: 4200, errorRatePercent: 8.4, technology: 'Anycast DNS' },
        { id: 'n2', name: 'gateway-ingress', type: 'gateway', status: 'degraded', latencyMs: 1840, throughputRps: 2800, errorRatePercent: 14.2, podCount: '8/8 Running', technology: 'NGINX Ingress' },
        { id: 'n3', name: 'eu-central-api', type: 'service', status: 'healthy', latencyMs: 42, throughputRps: 2600, errorRatePercent: 0.05, technology: 'Golang 1.22' },
        { id: 'n4', name: 'Origin Database', type: 'database', status: 'healthy', latencyMs: 8, throughputRps: 1200, errorRatePercent: 0.0, technology: 'CockroachDB' },
      ],
      edges: [
        { id: 'e1', source: 'n1', target: 'n2', latencyMs: 1840, status: 'degraded' },
        { id: 'e2', source: 'n2', target: 'n3', latencyMs: 42, status: 'healthy' },
        { id: 'e3', source: 'n3', target: 'n4', latencyMs: 8, status: 'healthy' },
      ],
    },
    telemetry: [
      { timestamp: '06:00', errorRate: 0.01, p95Latency: 45, p99Latency: 80, resourceSaturation: 24.0 },
      { timestamp: '06:05', errorRate: 2.4, p95Latency: 480, p99Latency: 820, resourceSaturation: 38.0 },
      { timestamp: '06:10', errorRate: 14.2, p95Latency: 1840, p99Latency: 2900, resourceSaturation: 45.0 },
    ],
    errorBudget: {
      targetSlo: 99.9,
      periodDays: 30,
      totalBudgetMinutes: 43.2,
      minutesBurned: 6.2,
      burnRateMultiplier: 2.5,
      estimatedExhaustionHours: 18.0,
    },
  },
  {
    id: 'inc-9484',
    title: 'P4: Redis Cluster Read Replica MaxMemory Thrashing',
    service: 'catalog-service',
    severity: 'P4',
    status: 'investigating',
    startedAt: '2026-08-26T05:00:00Z',
    durationMinutes: 60,
    affectedUsers: 850,
    revenueBurnRate: 95,
    logs: [
      {
        id: 'l30',
        timestamp: '05:00:11.890',
        level: 'WARN',
        service: 'catalog-service',
        pod: 'redis-node-03',
        message: 'maxmemory (8.00GB) reached - executing volatile-lru eviction of 14,820 keys/sec',
      },
    ],
    recentDeployments: [],
    diagnosis: {
      hypothesis:
        'Redis catalog read replica hit maxmemory threshold resulting in aggressive CPU-intensive key evictions.',
      confidence: 0.91,
      affectedService: 'catalog-service',
      failureMode: 'REDIS_MEMORY_SPIKE',
      evidenceFromLogs: ['maxmemory (8.00GB) reached - executing volatile-lru eviction'],
      blastRadius: {
        primaryImpact: 'Sub-second cache miss rate increased to 8%',
        secondaryImpact: ['Slight 50ms read latency increase on product search'],
        estimatedUsersAffected: 850,
        estimatedRevenuePerMin: 95,
      },
      remediationSteps: [
        {
          step: 1,
          action: 'Flush expired transient keys and increase cluster replica memory ceiling to 16GB',
          command: 'redis-cli -h redis-cluster.internal -p 6379 CONFIG SET maxmemory 16gb',
          expectedOutcome: 'Evictions halt and cache hit ratio returns to > 99.2%',
          risk: 'LOW',
        },
      ],
    },
    comms: {
      slackMessage: 'ℹ️ *P4 NOTICE:* Redis cache eviction spike mitigated by expanding maxmemory to 16GB.',
      executiveBrief: 'Low severity cache eviction resolved without business impact.',
      statusPageUpdate: 'All systems operational.',
    },
    topology: {
      nodes: [
        { id: 'n1', name: 'Global Traffic Edge', type: 'edge', status: 'healthy', latencyMs: 12, throughputRps: 5200, errorRatePercent: 0.0, technology: 'Cloudflare' },
        { id: 'n2', name: 'API Gateway', type: 'gateway', status: 'healthy', latencyMs: 25, throughputRps: 3800, errorRatePercent: 0.2, technology: 'Traefik' },
        { id: 'n3', name: 'catalog-service', type: 'service', status: 'healthy', latencyMs: 145, throughputRps: 2400, errorRatePercent: 1.8, podCount: '4/4 Running', technology: 'Node.js Fastify' },
        { id: 'n4', name: 'redis-read-replica', type: 'cache', status: 'degraded', latencyMs: 82, throughputRps: 8900, errorRatePercent: 8.0, technology: 'Redis 7.2 (8GB Saturated)' },
        { id: 'n5', name: 'catalog-postgres', type: 'database', status: 'healthy', latencyMs: 6, throughputRps: 620, errorRatePercent: 0.0, technology: 'PostgreSQL Aurora' },
      ],
      edges: [
        { id: 'e1', source: 'n1', target: 'n2', latencyMs: 12, status: 'healthy' },
        { id: 'e2', source: 'n2', target: 'n3', latencyMs: 25, status: 'healthy' },
        { id: 'e3', source: 'n3', target: 'n4', latencyMs: 82, status: 'degraded' },
        { id: 'e4', source: 'n3', target: 'n5', latencyMs: 6, status: 'healthy' },
      ],
    },
    telemetry: [
      { timestamp: '04:50', errorRate: 0.01, p95Latency: 22, p99Latency: 35, resourceSaturation: 74.0 },
      { timestamp: '04:55', errorRate: 0.05, p95Latency: 45, p99Latency: 68, resourceSaturation: 89.2 },
      { timestamp: '05:00', errorRate: 1.8, p95Latency: 145, p99Latency: 280, resourceSaturation: 99.4 },
    ],
    errorBudget: {
      targetSlo: 99.9,
      periodDays: 30,
      totalBudgetMinutes: 43.2,
      minutesBurned: 1.4,
      burnRateMultiplier: 1.2,
      estimatedExhaustionHours: 72.0,
    },
  },
];
