'use client';

import { useState } from 'react';
import { LegalAnalysis } from '@/types';
import { Download, Copy, Check, X, FileText, Printer } from 'lucide-react';

interface Props {
  analysis: LegalAnalysis;
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportReportModal({ analysis, isOpen, onClose }: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    return `# Legal Document Risk Analysis Report: ${analysis.docTitle}
**Document Type**: ${analysis.docType}
**Date Analyzed**: ${new Date(analysis.createdAt).toLocaleDateString()}
**Overall Risk Score**: ${analysis.riskScore}/100 (${analysis.riskVerdict})

---

## 1. Executive Summary
${analysis.executiveSummary}

### Balanced Strengths
${analysis.overallPros.map((p) => `- ${p}`).join('\n')}

### Red Flags & Risks
${analysis.overallCons.map((c) => `- ${c}`).join('\n')}

---

## 2. Flagged Dangerous Clauses (${analysis.dangerousClauses.length})
${analysis.dangerousClauses
  .map(
    (c, i) => `### ${i + 1}. [${c.severity}] ${c.title} (${c.category})
- **Exact Text Quote**: "${c.exactText}"
- **Plain English**: ${c.plainEnglish}
- **Legal Implication**: ${c.legalImplication}
- **Recommended Counter-Proposal**:
> ${c.counterProposal}
`
  )
  .join('\n')}

---

## 3. Missing Standard Protections (${analysis.missingClauses.length})
${analysis.missingClauses
  .map(
    (m, i) => `### ${i + 1}. [${m.importance}] ${m.clause}
- **Danger of Absence**: ${m.risk}
- **Industry Standard Recommendation**: ${m.standardRecommendation}
`
  )
  .join('\n')}

---

## 4. Section-by-Section Plain-English Breakdown
${analysis.sections
  .map(
    (s) => `### ${s.title} (Risk: ${s.riskLevel})
${s.plainEnglish}
- **Takeaway**: ${s.keyTakeaway}
`
  )
  .join('\n')}

---
*Report generated by ClauseWise.AI. This report is for educational purposes and does not constitute formal legal counsel.*
`;
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Legal_Risk_Report_${analysis.docTitle.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150 font-mono">
      <div className="p-6 sm:p-8 rounded-3xl bg-[#0d1117] border border-amber-500/40 max-w-xl w-full space-y-6 shadow-2xl relative">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-amber-400" />
            <h3 className="font-bold text-white text-base font-outfit">Export Negotiation Brief</h3>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white bg-slate-900 border border-slate-800 cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="space-y-3 text-xs text-slate-300">
          <p>
            Export a complete, lawyer-ready negotiation summary with all dangerous clause counter-proposals and missing protection requirements.
          </p>

          <div className="p-4 rounded-2xl bg-[#161b22] border border-slate-800 space-y-2">
            <div className="flex justify-between">
              <span className="text-slate-400">Target Document:</span>
              <strong className="text-white">{analysis.docTitle}</strong>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Risk Assessment:</span>
              <strong className="text-amber-400">{analysis.riskScore}/100</strong>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Flagged Clauses:</span>
              <strong className="text-rose-400">{analysis.dangerousClauses.length} items</strong>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
          <button
            onClick={handleDownloadMarkdown}
            className="p-3.5 rounded-xl bg-gradient-to-r from-amber-400 to-orange-500 hover:from-amber-300 hover:to-orange-400 text-black font-bold text-xs transition-all flex items-center justify-center gap-2 cursor-pointer shadow-md"
          >
            <Download className="w-4 h-4" />
            <span>Download .MD Brief</span>
          </button>

          <button
            onClick={handlePrint}
            className="p-3.5 rounded-xl bg-slate-900 border border-slate-700 hover:border-amber-500/40 text-slate-200 text-xs font-bold transition-all flex items-center justify-center gap-2 cursor-pointer"
          >
            <Printer className="w-4 h-4 text-amber-400" />
            <span>Print / PDF Export</span>
          </button>
        </div>

        <div className="text-center">
          <button
            onClick={handleCopyMarkdown}
            className="text-xs text-slate-400 hover:text-white underline cursor-pointer inline-flex items-center gap-1.5"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Full Markdown Text'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
