import { TestConfig, TestResult } from '@/types';

export interface BenchmarkPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  config: TestConfig;
  mockResult: TestResult;
}

export const BENCHMARK_PRESETS: BenchmarkPreset[] = [
  {
    id: 'preset_ecommerce',
    name: 'E-Commerce Catalog & Search API',
    category: 'High Throughput Read',
    description: 'High concurrency read workload simulating Black Friday shoppers querying product inventory.',
    icon: '🛍️',
    config: {
      id: 'cfg_ecommerce',
      title: 'E-Commerce Catalog & Search API Concurrency Test',
      url: 'https://dummyjson.com/products',
      method: 'GET',
      headers: [
        { key: 'Accept', value: 'application/json', enabled: true },
        { key: 'User-Agent', value: 'LoadPulse.AI/2.0', enabled: true },
      ],
      bodyType: 'none',
      authType: 'none',
      virtualUsers: 75,
      durationSeconds: 15,
      rampUpSeconds: 3,
      loadProfile: 'ramping_spike',
      timeoutMs: 5000,
    },
    mockResult: {
      id: 'res_ecommerce_1',
      config: {
        id: 'cfg_ecommerce',
        title: 'E-Commerce Catalog & Search API Concurrency Test',
        url: 'https://dummyjson.com/products',
        method: 'GET',
        headers: [{ key: 'Accept', value: 'application/json', enabled: true }],
        bodyType: 'none',
        authType: 'none',
        virtualUsers: 75,
        durationSeconds: 15,
        rampUpSeconds: 3,
        loadProfile: 'ramping_spike',
        timeoutMs: 5000,
      },
      startedAt: new Date(Date.now() - 3600000).toISOString(),
      completedAt: new Date(Date.now() - 3600000 + 15000).toISOString(),
      status: 'completed',
      totalRequests: 2840,
      successfulRequests: 2812,
      failedRequests: 28,
      errorRate: 0.98,
      avgRps: 189.3,
      peakRps: 242.0,
      totalDataTransferMb: 14.8,
      percentiles: {
        min: 68,
        p50: 184,
        p75: 310,
        p90: 540,
        p95: 890,
        p99: 1420,
        p999: 2100,
        max: 2450,
        mean: 236.4,
      },
      statusCodes: [
        { code: 200, count: 2812, description: 'OK — Successful Catalog Query', isError: false },
        { code: 429, count: 28, description: 'Too Many Requests — Rate Limited', isError: true },
      ],
      recentErrors: [
        { timestamp: '14:22:04', statusCode: 429, message: 'HTTP 429: Cloudflare edge rate limit exceeded for IP slot.' },
      ],
      timeSeries: [
        { timestampSec: 1, activeVus: 15, rps: 45, p50Ms: 120, p90Ms: 190, p95Ms: 240, p99Ms: 380, errorRatePercent: 0, bytesPerSec: 145000 },
        { timestampSec: 3, activeVus: 45, rps: 130, p50Ms: 150, p90Ms: 280, p95Ms: 410, p99Ms: 650, errorRatePercent: 0, bytesPerSec: 420000 },
        { timestampSec: 6, activeVus: 75, rps: 210, p50Ms: 180, p90Ms: 480, p95Ms: 780, p99Ms: 1240, errorRatePercent: 0.4, bytesPerSec: 780000 },
        { timestampSec: 9, activeVus: 75, rps: 242, p50Ms: 210, p90Ms: 560, p95Ms: 920, p99Ms: 1520, errorRatePercent: 1.2, bytesPerSec: 910000 },
        { timestampSec: 12, activeVus: 75, rps: 235, p50Ms: 195, p90Ms: 520, p95Ms: 880, p99Ms: 1410, errorRatePercent: 0.9, bytesPerSec: 880000 },
        { timestampSec: 15, activeVus: 20, rps: 95, p50Ms: 140, p90Ms: 240, p95Ms: 320, p99Ms: 510, errorRatePercent: 0, bytesPerSec: 320000 },
      ],
      aiAnalysis: {
        verdict: 'PASS',
        performanceScore: 88,
        summary: 'Target API performed admirably with 189.3 avg RPS. P99 tail latency increased beyond 50 VUs due to origin DB serialization.',
        bottlenecks: [
          {
            id: 'b1',
            type: 'MISSING_CACHE_LAYER',
            severity: 'MEDIUM',
            title: 'Origin Cache-Control Header Missing',
            evidence: 'Identical product catalog queries triggered full backend execution on every request.',
            rootCause: 'Lack of Edge Cloudflare Cache-Control TTL headers for public catalog queries.',
            remediationStep: 'Add `Cache-Control: public, s-maxage=300, stale-while-revalidate=60` to cache responses at CDN edge.',
            estimatedGain: '4x throughput boost & 80% P99 reduction',
          },
        ],
        architecturalSuggestions: [
          'Implement Redis cluster read-replica caching for top 100 search items',
          'Tune upstream TCP keep-alive sockets to avoid TLS handshake overhead',
        ],
      },
    },
  },
  {
    id: 'preset_slow_query',
    name: 'Database Contention & Lock Stress',
    category: 'High Latency / Bottleneck',
    description: 'Simulates heavy unindexed database joins or slow microservice cascade under concurrency.',
    icon: '🐢',
    config: {
      id: 'cfg_slow',
      title: 'Database Contention & Lock Stress Test',
      url: 'https://httpbin.org/delay/1',
      method: 'GET',
      headers: [{ key: 'Accept', value: 'application/json', enabled: true }],
      bodyType: 'none',
      authType: 'none',
      virtualUsers: 40,
      durationSeconds: 15,
      rampUpSeconds: 2,
      loadProfile: 'stress',
      timeoutMs: 5000,
    },
    mockResult: {
      id: 'res_slow_1',
      config: {
        id: 'cfg_slow',
        title: 'Database Contention & Lock Stress Test',
        url: 'https://httpbin.org/delay/1',
        method: 'GET',
        headers: [],
        bodyType: 'none',
        authType: 'none',
        virtualUsers: 40,
        durationSeconds: 15,
        rampUpSeconds: 2,
        loadProfile: 'stress',
        timeoutMs: 5000,
      },
      startedAt: new Date(Date.now() - 7200000).toISOString(),
      completedAt: new Date(Date.now() - 7200000 + 15000).toISOString(),
      status: 'completed',
      totalRequests: 480,
      successfulRequests: 420,
      failedRequests: 60,
      errorRate: 12.5,
      avgRps: 32.0,
      peakRps: 38.0,
      totalDataTransferMb: 2.1,
      percentiles: {
        min: 1020,
        p50: 1240,
        p75: 1850,
        p90: 2900,
        p95: 3800,
        p99: 4750,
        p999: 4950,
        max: 5000,
        mean: 1840.0,
      },
      statusCodes: [
        { code: 200, count: 420, description: 'OK — Delayed Response', isError: false },
        { code: 504, count: 60, description: 'Gateway Timeout (5s threshold)', isError: true },
      ],
      recentErrors: [
        { timestamp: '11:15:02', statusCode: 504, message: 'HTTP 504: Gateway Timeout after 5000ms socket wait.' },
      ],
      timeSeries: [
        { timestampSec: 1, activeVus: 10, rps: 9, p50Ms: 1050, p90Ms: 1120, p95Ms: 1200, p99Ms: 1350, errorRatePercent: 0, bytesPerSec: 28000 },
        { timestampSec: 5, activeVus: 30, rps: 28, p50Ms: 1180, p90Ms: 2400, p95Ms: 3100, p99Ms: 4100, errorRatePercent: 6.5, bytesPerSec: 84000 },
        { timestampSec: 10, activeVus: 40, rps: 35, p50Ms: 1350, p90Ms: 3400, p95Ms: 4200, p99Ms: 4900, errorRatePercent: 18.2, bytesPerSec: 105000 },
        { timestampSec: 15, activeVus: 10, rps: 12, p50Ms: 1100, p90Ms: 1400, p95Ms: 1800, p99Ms: 2200, errorRatePercent: 0, bytesPerSec: 35000 },
      ],
      aiAnalysis: {
        verdict: 'CRITICAL_FAIL',
        performanceScore: 42,
        summary: 'Catastrophic latency degradation and 12.5% 504 Gateway Timeouts under moderate concurrency.',
        bottlenecks: [
          {
            id: 'b_db_pool',
            type: 'DATABASE_CONNECTION_POOL',
            severity: 'CRITICAL',
            title: 'Connection Pool Starvation & Queue Overflow',
            evidence: 'P99 latency spiked 4x higher than P50, with 60 requests aborted due to 5s gateway timeout.',
            rootCause: 'PostgreSQL max_connections bottleneck and synchronous blocking queries.',
            remediationStep: 'Deploy PgBouncer in transaction pooling mode. Increase pool size from 10 to 50.',
            estimatedGain: '70% latency reduction & eliminate 504 timeouts',
          },
        ],
        architecturalSuggestions: [
          'Add compound B-tree index on query filter columns',
          'Implement circuit breaker pattern (Resilience4j / Opossum) with exponential backoff',
        ],
      },
    },
  },
];
